language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
      organization: "unimibsoftengcourse1920" # the key of the org you chose at step #3
      token:
        secure: $travis # encrypted value of your token
script:
  - mvn sonar:sonar